#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use App\MultiplyBy5Command;
use Symfony\Component\Console\Application;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Reference;
use App\Multiply;

$containerBuilder = new ContainerBuilder();
$containerBuilder->register('multiply', Multiply::class);

$containerBuilder->register('multiply_by_5_command', MultiplyBy5Command::class);
$containerBuilder->register('multiply_by_2_command', MultiplyBy2Command::class)
  ->addArgument(new Reference('multiply'));

$containerBuilder
    ->register('application', Application::class);


$containerBuilder->get('application')->run();
