#!/usr/bin/env php
<?php
// application.php

require __DIR__ . '/vendor/autoload.php';

use App\Multiply;
use App\MultiplyBy2Command;
use App\MultiplyBy5Command;
use App\MultiplyBy7Command;
use App\MultiplyBy8Command;
use Symfony\Component\Console\Application;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Reference;

$containerBuilder = new ContainerBuilder();
$containerBuilder->register('multiply', Multiply::class);

$containerBuilder->register('multiply_by_5_command', MultiplyBy5Command::class)
    ->addArgument(new Reference('multiply'));
$containerBuilder->register('multiply_by_2_command', MultiplyBy2Command::class)
    ->addArgument(new Reference('multiply'));

$containerBuilder->register('multiply_by_8_command', MultiplyBy8Command::class)
    ->addArgument(new Reference('multiply'));
$containerBuilder->register('multiply_by_7_command', MultiplyBy7Command::class)
    ->addArgument(new Reference('multiply'));

$containerBuilder
    ->register('application', Application::class)
    ->addMethodCall('add', [new Reference('multiply_by_5_command')])
    ->addMethodCall('add', [new Reference('multiply_by_2_command')])
    ->addMethodCall('add', [new Reference('multiply_by_8_command')])
    ->addMethodCall('add', [new Reference('multiply_by_7_command')]);


$containerBuilder->get('application')->run();
